version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/redis/:/var/lib/redis/data
    networks:
      public_net:
        ipv4_address: 192.168.21.11
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      public_net:
        ipv4_address: 192.168.21.12
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    container_name: bitcoinersbest-rails
    image: ruby:2.6.4
    volumes:
      - .:/myapp:delegated
    ports:
      - 3001:3001
      - 3035:3035
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
    networks:
      public_net:
        ipv4_address: 192.168.21.13

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.21.0/24
